opencgl.current.version=v${software-version}-${build.timestamp}
opencgl.upgrade.url=http://upgrade.tool-graphical.top/OpenCGL/version.properties
opencgl.help.url=https://gitee.com/chance_w/OpenCGL_New/blob/main/README.md